/*******************************************************************************
* Copyright (C) 2021 the Eclipse BaSyx Authors
*
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 * 
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 * LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*
* SPDX-License-Identifier: MIT
******************************************************************************/
package org.eclipse.basyx.testsuite.regression.aas.factory.xml;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;

import org.eclipse.basyx.aas.factory.xml.XMLToMetamodelConverter;
import org.eclipse.basyx.aas.metamodel.api.parts.asset.AssetKind;
import org.eclipse.basyx.aas.metamodel.api.parts.asset.IAsset;
import org.eclipse.basyx.submodel.metamodel.api.ISubmodel;
import org.eclipse.basyx.submodel.metamodel.map.submodelelement.operation.Operation;
import org.junit.Test;

/**
 * This tests the workarounds implemented in XML deserialization to handle .xml
 * files generated by the AASXPackageExplorer
 * 
 * @author conradi
 *
 */
public class TestAASXPackageExplorerCompatibility {

	private String xmlInWorkaroundsPath = "src/test/resources/aas/factory/xml/inWorkarounds.xml";

	@Test
	public void testAASXPackageExplorerWorkarounds() throws Exception {
		String xml = new String(Files.readAllBytes(Paths.get(xmlInWorkaroundsPath)));
		XMLToMetamodelConverter converter = new XMLToMetamodelConverter(xml);
		List<IAsset> assetList = converter.parseAssets();
		List<ISubmodel> submodelList = converter.parseSubmodels();

		assertEquals(1, assetList.size());
		IAsset asset = assetList.iterator().next();
		checkAsset(asset);

		assertEquals(1, submodelList.size());
		ISubmodel sm = submodelList.iterator().next();
		checkOperation(sm);
	}

	private void checkOperation(ISubmodel sm) {
		Operation op = (Operation) sm.getSubmodelElement("operation_ID");
		assertNotNull(op);
		assertEquals(2, op.getInputVariables().size());
		assertEquals(1, op.getOutputVariables().size());
	}

	private void checkAsset(IAsset asset) {
		assertEquals(asset.getAssetKind(), AssetKind.TYPE);
	}

}
